import { useEffect, useState, type ReactNode } from "react";
import QRCode from "qrcode";
import { commerceCases, commerceChain, commerceChecks, commerceValueBlocks, devAdapterCatalog, devCompositions, devModuleCatalog, devPrinciples, devVerticalCatalog, howSteps, questions, pymiaMethod, sellerBusinessChain, sellerGrowthSignals, sellerPainPoints, sellerSignalExamples, smbAreas, smbCases, smbExcel, smbProblems, smbTools, SURVEY_URL, vtvPublicSteps, WHATSAPP_URL } from "./data/content";

type Route = "/" | "/ecommerce" | "/pymes" | "/devs";
type Theme = "commerce" | "smb" | "devs";

const pageMeta: Record<Route, { title: string; description: string }> = {
  "/": { title: "PymIA — Operaciones conectadas", description: "PymIA conecta las herramientas que tu empresa ya usa y construye la pieza que falta." },
  "/ecommerce": { title: "E-commerce — PymIA", description: "Conectá marketplaces, sistemas y datos para vender online con menos fricción y más control." },
  "/pymes": { title: "PyMEs — PymIA", description: "Conectá administración, datos y procesos para reducir trabajo manual y ganar control." },
  "/devs": { title: "Devs — PymIA", description: "Construí soluciones empresariales con módulos, verticales y adaptadores reutilizables." },
};

function Contact({ label = "Contanos qué querés resolver" }: { label?: string }) {
  return <a className="button" href={WHATSAPP_URL}>{label} <span aria-hidden="true">↗</span></a>;
}
function Status({ children }: { children: string }) { return <span className="status-badge">{children}</span>; }

function Header() {
  return <header className="site-header shell"><a className="brand" href="/" aria-label="PymIA, volver al inicio"><img src="/logopymia2.jpg" width="56" height="56" alt="Logo de PymIA" fetchPriority="high" /><span><strong>PymIA</strong><small>Operaciones conectadas</small></span></a><nav aria-label="Navegación principal"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href="/#how">Cómo trabajamos</a><a href="/#contacto">Contacto</a><a className="nav-cta" href={SURVEY_URL}>Quiero mi VTV ↗</a></nav></header>;
}
function Footer() {
  return <footer className="shell site-footer"><span>PymIA — Buenos Aires, Argentina.</span><nav aria-label="Navegación del pie"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href={SURVEY_URL}>VTV</a><a href="/#contacto">Contacto</a></nav><a href="/#top">Volver arriba ↑</a></footer>;
}
function CommercialQr() {
  const [qr, setQr] = useState("");
  useEffect(() => { let active = true; void QRCode.toDataURL(SURVEY_URL, { width: 640, margin: 4, errorCorrectionLevel: "M", color: { dark: "#162b29", light: "#ffffff" } }).then((value) => { if (active) setQr(value); }).catch(() => { if (active) setQr(""); }); return () => { active = false; }; }, []);
  return <a className="qr-link" href={SURVEY_URL} aria-label="Abrir la VTV gratuita de PymIA">{qr && <img src={qr} width="240" height="240" alt="Código QR para abrir la VTV gratuita de PymIA" />}<span>Escaneá o tocá para completar la VTV gratuita ↗</span></a>;
}
function TrustBlock() {
  return <section className="trust-section shell section"><div><p className="eyebrow">Una forma de trabajar</p><h2>La IA ayuda a entender. PymIA controla lo que tiene que ser exacto.</h2></div><div className="trust-list"><p><strong>Evidencia.</strong> No afirmamos lo que no podemos revisar.</p><p><strong>Trazabilidad.</strong> Cada proceso deja una historia que se puede seguir.</p><p><strong>Integración.</strong> Empezamos por lo que ya existe.</p></div></section>;
}
function HowSection() {
  return <section className="how-section shell section" id="how"><div className="section-head"><div><p className="eyebrow">Cómo trabaja PymIA</p><h2>Conectar primero. Decidir mejor.</h2></div><p>Evidencia, trazabilidad y control humano: la tecnología ayuda a entender y ejecutar; la persona decide cuando corresponde.</p></div><div className="process-rail">{howSteps.map(([title, copy], index) => <article key={title}><span className="rail-dot" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>;
}
function Home() {
  return <><main id="main-content"><section className="hero shell"><div className="hero-copy"><p className="eyebrow">PymIA / operaciones conectadas</p><h1>Tu empresa ya tiene herramientas.<br /><em>PymIA hace que trabajen juntas.</em></h1><p className="hero-lede">Conectamos e-commerce, Excel, sistemas, automatizaciones e IA para reducir trabajo manual, entender lo que está pasando y construir soluciones sobre lo que ya usás.</p><div className="actions"><Contact /><a className="button button-secondary" href="#audiences">Ver soluciones ↓</a></div></div><div className="hero-aside"><div className="aside-line"><span>01</span><span>Conectar antes que reemplazar</span></div><div className="aside-line"><span>02</span><span>Reglas claras donde importan</span></div><div className="aside-line"><span>03</span><span>Personas con el control</span></div></div></section><section className="doorways shell" id="audiences"><div className="doorways-intro"><p className="eyebrow">Una marca, tres caminos</p><p>Elegí la conversación que más se parece a tu operación.</p></div><div className="doorway-grid"><a className="doorway doorway-commerce" href="/ecommerce"><span className="doorway-kicker">E-commerce</span><strong>Vendé online con menos fricción y más control.</strong><span>Marketplaces, stock, rentabilidad y datos que trabajan juntos.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar E-commerce ↗</b></a><a className="doorway doorway-smb" href="/pymes"><span className="doorway-kicker">PyMEs</span><strong>Menos trabajo manual. Más control del negocio.</strong><span>Administración, procesos y decisiones sobre información ordenada.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar soluciones para PyMEs ↗</b></a><a className="doorway doorway-devs" href="/devs"><span className="doorway-kicker">Devs</span><strong>No construyas cada solución desde cero.</strong><span>Módulos, verticales y adaptadores para implementar mejor.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar PymIA para Devs ↗</b></a></div></section><HowSection /><TrustBlock /><section className="final-section" id="contacto"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>Contanos qué querés resolver.</h2><p>Vemos qué parte de tu operación conviene conectar, ordenar o construir.</p><Contact /><p className="survey-link">También podés empezar con una revisión VTV gratuita.</p></div><CommercialQr /></div></section></main></>;
}
function ProductHero({ theme, eyebrow, title, copy, children }: { theme: Theme; eyebrow: string; title: string; copy: string; children?: ReactNode }) {
  return <section className={`product-hero section-${theme}`}><div className="shell product-hero-inner"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-lede">{copy}</p>{children}</div><div className="product-signal"><span>PYMIA</span><strong>{theme === "commerce" ? "01" : theme === "smb" ? "02" : "03"}</strong><small>línea comercial</small></div></div></section>;
}
function CommercePage() {
  return <main id="main-content">
    <ProductHero theme="commerce" eyebrow="E-commerce / sellers" title="Vendé online con más control sobre lo que realmente ganás." copy="PymIA conecta los datos de tu operación para mostrarte dónde perdés margen, tiempo o control y qué conviene corregir primero, sin obligarte a reemplazar las herramientas que ya usás.">
      <div className="actions"><a className="button button-commerce" href={SURVEY_URL}>Quiero mi VTV gratuita ↗</a><a className="button button-secondary" href="#commerce-review">Ver qué podemos revisar ↓</a></div>
    </ProductHero>
    <section className="seller-thesis shell section" id="seller-thesis"><div className="section-head"><div><p className="eyebrow">La realidad del seller</p><h2>Tu negocio crece. Tu tiempo se achica. Tu margen necesita control.</h2></div><p>PymIA conecta ventas, costos y operación para mostrarte dónde estás perdiendo margen, tiempo o control y qué conviene resolver primero.</p></div><p className="seller-thesis-lead">Vender más no alcanza si cada venta te deja menos margen, te consume más stock y exige más de tu tiempo.</p><p className="seller-equation">FACTURAR MÁS ≠ GANAR MÁS</p><div className="growth-rail">{sellerGrowthSignals.map((item, index) => <span key={item} className={index === sellerGrowthSignals.length - 1 ? "growth-rail-final" : ""}>{item}</span>)}</div></section>
    <section className="commerce-problems shell section" id="commerce-review">
      <div className="section-head"><div><p className="eyebrow">¿Te pasa esto?</p><h2>Vender más no sirve si cada venta te deja menos margen y menos tiempo.</h2></div><p>Si te reconocés acá, no necesitás otra pantalla: necesitás conectar la operación que ya tenés.</p></div>
      <ul className="seller-pain-list">{sellerPainPoints.map((item, index) => <li key={item}><span className="problem-index">0{index + 1}</span><p>{item}</p></li>)}</ul>
    </section>
    <section className="seller-mirror section"><div className="shell"><p className="seller-mirror-copy">Si para entender cómo está tu negocio tenés que abrir seis sistemas distintos, el problema no es la falta de datos. Es que nadie los está conectando.</p></div></section>
    <section className="seller-fragmentation section section-commerce"><div className="shell"><div className="section-head"><div><p className="eyebrow">Demasiadas herramientas</p><h2>Tu problema puede no ser que te falten herramientas. Puede ser que tengas demasiadas que no se hablan entre sí.</h2></div><p>Trabajamos sobre la operación que ya tenés. PymIA ayuda a conectar señales, detectar contradicciones y mostrar qué requiere atención.</p></div><div className="signal-stack"><span>Mercado Libre</span><b>+</b><span>Mercado Pago</span><b>+</b><span>Ads</span><b>+</b><span>ERP</span><b>+</b><span>Integrador</span><b>+</b><span>Excel</span><b>+</b><span>Costos reales</span><i>↓</i><strong>PYMIA</strong><i>↓</i><em>Conecta señales · Detecta contradicciones · Muestra qué requiere atención</em></div></div></section>
    <section className="pymia-control section section-commerce"><div className="shell"><div className="section-head"><div><p className="eyebrow">Lo que hace PymIA</p><h2>No necesitás mirar más dashboards. Necesitás saber qué mirar.</h2></div><p>La información se transforma en una prioridad concreta, sin prometer más de lo que la evidencia permite.</p></div><div className="complexity-formula"><span>MÁS VENTAS</span><b>+</b><span>MÁS COMPLEJIDAD</span><b>+</b><span>MENOS TIEMPO</span><b>+</b><span>MÁRGENES MÁS FINOS</span><i></i><strong>MENOS CONTROL</strong></div><div className="pymia-method"><span>PYMIA</span>{pymiaMethod.map((item) => <span key={item}>→ {item}</span>)}<small>El owner decide.</small></div><p className="control-preserve">Automatizá lo repetible. Conservá control sobre lo importante.</p></div></section>
    <section className="signal-examples shell section"><div className="section-head"><div><p className="eyebrow">Los datos solos no alcanzan</p><h2>El problema aparece en la relación entre esos datos.</h2></div><p>Son señales que conviene investigar, no diagnósticos automáticos.</p></div><div className="signal-example-grid">{sellerSignalExamples.map(([relation, meaning]) => <article key={relation}><strong>{relation}</strong><span>↓</span><p>{meaning}</p></article>)}</div></section>
    <section className="business-chain section section-commerce"><div className="shell"><div className="section-head"><div><p className="eyebrow">Fundamentos del negocio</p><h2>Ninguna variable funciona aislada.</h2></div><p>Una caída de ventas puede estar relacionada con demanda, conversión, precio, stock, publicidad, estacionalidad, logística o reputación.</p></div><div className="business-chain-rail">{sellerBusinessChain.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, "0")}</b>{item}</span>)}</div></div></section>
    <section className="healthy-growth shell section"><div><p className="eyebrow">Crecimiento saludable</p><h2>Crecer bien es sostener el negocio mientras aumenta el volumen.</h2></div><div><p className="healthy-growth-question">¿Tu operación puede seguir creciendo sin romper margen, stock, caja, operación o tu tiempo?</p><a className="text-link" href={SURVEY_URL}>Empezá por una VTV ↗</a></div></section>
    <section className="commerce-meli section section-commerce">
      <div className="shell section-inner"><div className="section-head"><div><p className="eyebrow">Mercado Libre</p><h2>Leemos la operación como una cadena.</h2></div><p>Una diferencia en la publicación puede terminar afectando el margen. Miramos el recorrido completo para encontrar la señal útil.</p></div>
        <ol className="operation-chain">{commerceChain.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></li>)}</ol>
        <div className="operation-detail"><div><p className="eyebrow">Qué podemos revisar</p><p>Publicaciones, precios, órdenes, stock, Full / Flex, cargos, cobros, reclamos, devoluciones y conciliaciones.</p></div><ul className="tag-list commerce-checks">{commerceChecks.map((item) => <li key={item}>{item}</li>)}</ul><p className="commerce-note">Mercado Experience es nuestro contexto de entrada; la lectura sirve para entender tu operación completa.</p></div>
      </div>
    </section>
    <section className="vtv-feature section" id="vtv-review"><div className="shell vtv-feature-inner"><div><p className="eyebrow">La primera decisión</p><h2>Tu primera revisión: VTV PymIA.</h2><p>Contanos cómo operás, conectamos datos reales y recibís las 3 prioridades principales para saber qué corregir primero.</p><a className="button button-vtv" href={SURVEY_URL}>Hacer mi VTV ↗</a></div><div className="vtv-outcome"><div className="vtv-steps"><article><span>01</span><strong>Contanos cómo operás</strong><p>Canales, herramientas y el problema que más te preocupa.</p></article><article><span>02</span><strong>Conectamos datos reales</strong><p>Ordenamos la evidencia disponible sin pedirte cambiar todo.</p></article><article><span>03</span><strong>Recibís tus 3 prioridades</strong><p>Una lectura concreta para decidir el siguiente paso.</p></article></div><div className="vtv-deliverables"><span>Qué está sólido</span><span>Qué requiere atención</span><span>Qué no puede verificarse</span><span>Qué corregir primero</span></div></div></div></section>
    <section className="vtv-process section section-commerce"><div className="shell"><div className="section-head"><div><p className="eyebrow">Cómo funciona la VTV</p><h2>Explicamos antes de pedir. Mostramos evidencia antes de concluir.</h2></div><p>Una revisión guiada para entender riesgos, pérdidas de control y oportunidades de mejora; no un score mágico ni una auditoría automática.</p></div><ol className="vtv-process-list">{vtvPublicSteps.map(([title, copy], index) => <li key={title}><b>{String(index + 1).padStart(2, "0")}</b><strong>{title}</strong><span>{copy}</span></li>)}</ol><p className="vtv-process-note">PymIA es la capa que conecta información separada para ayudarte a entender qué cambió, por qué importa y dónde mirar primero. Vos decidís cualquier cambio.</p></div></section>
    <section className="commerce-value shell section" id="commerce-value"><div className="section-head"><div><p className="eyebrow">Dónde podemos aportar claridad</p><h2>Una lectura útil antes de otra herramienta.</h2></div><p>Organizamos la conversación en cuatro frentes para que cada hallazgo tenga una decisión posible.</p></div><div className="value-list">{commerceValueBlocks.map(([title, copy], index) => <article key={title}><span className="value-index">0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="other-marketplaces section"><div className="shell other-marketplaces-inner"><div><p className="eyebrow">Más adelante</p><h2>Mercado Libre hoy. Más canales cuando tu operación lo necesite.</h2><p>Tiendanube, Shopify y otros canales pueden entrar después, cuando la base esté ordenada. No hace falta prometerlo antes.</p></div></div></section>
    <section className="commerce-cases shell section"><div className="section-head"><div><p className="eyebrow">Casos concretos</p><h2>La pregunta cambia según tu operación.</h2></div><p>El punto de partida es distinto; la prioridad tiene que ser visible.</p></div><div className="case-list">{commerceCases.map((item, index) => <article key={item}><span>0{index + 1}</span><p>{item}</p></article>)}</div></section>
    <section className="final-section commerce-final"><div className="shell final-grid"><div><p className="eyebrow">Empezá por una revisión</p><h2>Quiero hacer mi VTV.</h2><p>Empezá descubriendo las 3 prioridades que hoy más pueden estar afectando tu margen, tu tiempo y tu control operativo.</p><a className="button" href={SURVEY_URL}>Quiero hacer mi VTV ↗</a></div></div></section>
  </main>;
}
function PymesPage() {
  return <main id="main-content">
    <ProductHero theme="smb" eyebrow="PyMEs / administración" title="Tu empresa no necesita otro sistema. Necesita dejar de trabajar dos veces." copy="PymIA conecta Excel, administración, cobros, ventas, stock y sistemas existentes para reducir tareas manuales, ordenar información y mostrarte dónde hay diferencias o problemas.">
      <div className="actions"><a className="button button-smb" href={WHATSAPP_URL}>Contanos qué querés resolver ↗</a><a className="button button-secondary" href="#smb-problems">Ver problemas que podemos ordenar ↓</a></div>
    </ProductHero>
    <section className="smb-problems shell section" id="smb-problems"><div className="section-head"><div><p className="eyebrow">Problemas reales</p><h2>La operación se vuelve pesada cuando cada dato vive separado.</h2></div><p>Empezamos por hacer visible el trabajo que hoy se repite y las diferencias que nadie puede explicar.</p></div><div className="smb-problem-list">{smbProblems.map(([title, copy], index) => <article key={title}><span className="smb-index">0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="smb-tools section section-smb" id="smb-tools"><div className="shell section-inner"><div className="section-head"><div><p className="eyebrow">Mensaje central</p><h2>Conectamos lo que ya usás.</h2></div><p>Encontramos el hilo entre tus herramientas y el proceso real, sin obligarte a reemplazar todo tu negocio para empezar a mejorar.</p></div><div className="tool-cloud">{smbTools.map((tool) => <span key={tool}>{tool}</span>)}</div><p className="smb-tools-note">No necesitás reemplazar todo tu negocio para empezar a mejorar.</p></div></section>
    <section className="smb-areas shell section" id="smb-areas"><div className="section-head"><div><p className="eyebrow">Cuatro áreas de valor</p><h2>Del dato disperso a una decisión posible.</h2></div><p>Cada frente tiene un resultado concreto y un alcance visible.</p></div><div className="smb-area-list">{smbAreas.map(([title, headline, copy], index) => <article key={title}><span className="smb-index">0{index + 1}</span><div><p className="eyebrow">{title}</p><h3>{headline}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="excel-feature section section-smb" id="smb-excel"><div className="shell excel-feature-inner"><div><p className="eyebrow">Excel e inteligencia</p><h2>Si tu empresa vive en Excel, no significa que tengas que tirarlo.</h2><p>PymIA puede usar planillas y exportaciones como fuente de datos para analizar ventas, costos, márgenes, rentabilidad, inconsistencias y reportes.</p></div><div className="excel-panel"><Status>PILOTO</Status><ul>{smbExcel.map((item) => <li key={item}>{item}</li>)}</ul><p>El alcance se define con evidencia: algunas piezas están en piloto, en desarrollo o próximas.</p></div></div></section>
    <section className="smb-cases shell section" id="smb-cases"><div className="section-head"><div><p className="eyebrow">Casos concretos</p><h2>El problema cambia según el rubro.</h2></div><p>No prometemos soluciones completas: mostramos dónde PymIA puede ayudar a integrar y ordenar.</p></div><div className="smb-case-list">{smbCases.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="smb-flow section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Cómo trabajamos</p><h2>Primero entendemos. Después automatizamos.</h2></div><p>La automatización tiene sentido cuando el proceso y sus diferencias ya son visibles.</p></div><ol className="smb-flow-list"><li><span>01</span><strong>Lo que ya usás</strong></li><li><span>02</span><strong>Conectamos</strong></li><li><span>03</span><strong>Entendemos el proceso</strong></li><li><span>04</span><strong>Detectamos diferencias</strong></li><li><span>05</span><strong>Automatizamos lo repetible</strong></li></ol><p className="smb-flow-note">Primero entendemos cómo trabaja tu empresa. Después decidimos qué vale la pena automatizar.</p></div></section>
    <section className="final-section smb-final"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>¿Dónde estás perdiendo más tiempo hoy?</h2><p>Contanos el problema y vemos qué información o proceso conviene ordenar primero.</p><a className="button" href={WHATSAPP_URL}>Contanos tu problema ↗</a></div></div></section>
  </main>;
}
function DevsPage() {
  return <main id="main-content">
    <ProductHero theme="devs" eyebrow="Devs / implementadores" title="Construí soluciones empresariales sin empezar cada vez desde cero." copy="Combiná módulos de negocio, conocimiento vertical e integraciones para resolver problemas reales de PyMEs más rápido."><div className="actions"><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a><a className="button button-secondary" href="#dev-composition">Ver cómo se compone una solución ↓</a></div></ProductHero>
    <section className="dev-composition section section-devs" id="dev-composition"><div className="shell"><p className="eyebrow">La idea central</p><h2>Componé primero. Personalizá después.</h2><div className="formula-stage"><div className="formula-line"><span>MÓDULO</span><b>+</b><span>VERTICAL</span><b>+</b><span>ADAPTER</span></div><div className="formula-rule" /><strong>SOLUCIÓN</strong></div><div className="composition-example"><p className="eyebrow">Ejemplo conceptual</p><div><span>PRESUPUESTOS</span><b>+</b><span>TALLER MECÁNICO</span><b>+</b><span>WHATSAPP</span></div><strong>Solución para tomar, cotizar y seguir trabajos</strong></div></div></section>
    <section className="dev-layers-section shell section" id="dev-layers"><div className="section-head"><div><p className="eyebrow">Tres piezas</p><h2>Una solución clara, con alcance visible.</h2></div><p>El estado de cada pieza importa: estos son módulos, packs y conexiones posibles, no promesas de producto terminado.</p></div><div className="dev-layers-catalog"><article className="layer-card"><div className="layer-heading"><span className="layer-index">01</span><div><p className="card-kicker">Proceso reutilizable</p><h3>Módulos</h3></div></div><p>El módulo resuelve un proceso empresarial reutilizable.</p><ul className="dev-catalog">{devModuleCatalog.map(([name, status]) => <li key={name}><span>{name}</span><Status>{status}</Status></li>)}</ul></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">02</span><div><p className="card-kicker">Contexto de rubro</p><h3>Vertical Packs</h3></div></div><p>El Vertical Pack aporta lenguaje, objetos, reglas y contexto de un rubro.</p><ul className="dev-catalog">{devVerticalCatalog.map(([name, status]) => <li key={name}><span>{name}</span><Status>{status}</Status></li>)}</ul></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">03</span><div><p className="card-kicker">Conexión existente</p><h3>Adapters</h3></div></div><p>El adapter conecta la solución con la herramienta que el negocio ya usa.</p><ul className="dev-catalog">{devAdapterCatalog.map(([name, status]) => <li key={name}><span>{name}</span><Status>{status}</Status></li>)}</ul></article></div></section>
    <section className="dev-audiences section section-devs"><div className="shell"><div className="section-head"><div><p className="eyebrow">Para quién es</p><h2>Construí sobre una base que ya entiende el negocio.</h2></div><p>Una forma de entregar más rápido sin rehacer la lógica empresarial básica en cada cliente.</p></div><div className="dev-audience-cards"><article><p className="eyebrow">Freelancers</p><h3>Entregá más rápido sin rehacer lógica empresarial básica en cada cliente.</h3></article><article><p className="eyebrow">Agencias / implementadores IA</p><h3>Componé soluciones verticales sobre piezas reutilizables.</h3></article><article><p className="eyebrow">Software factories pequeñas</p><h3>Usá capacidades empresariales como base para proyectos específicos.</h3></article></div></div></section>
    <section className="dev-compositions shell section"><div className="section-head"><div><p className="eyebrow">Ejemplos de composición</p><h2>La combinación cambia según el problema.</h2></div><p>Son ejemplos conceptuales para mostrar cómo se arma una solución cuando las capacidades todavía están en piloto o desarrollo.</p></div><div className="composition-list">{devCompositions.map(([formula, outcome], index) => <article key={formula}><span>0{index + 1}</span><h3>{formula}</h3><strong>→ {outcome}</strong></article>)}</div></section>
    <section className="dev-why section"><div className="shell dev-why-inner"><div><p className="eyebrow">Por qué PymIA</p><h2>No te damos sólo código. Te damos contexto empresarial reutilizable.</h2><p>Procesos de negocio, vocabulario vertical, reglas, estructuras de datos, integraciones, evidencia y componentes que podés volver a usar.</p></div><ul className="dev-principles">{devPrinciples.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="dev-build section section-devs"><div className="shell"><div className="section-head"><div><p className="eyebrow">Cómo se construye</p><h2>Del problema real a una entrega concreta.</h2></div><p>Componé primero. Personalizá después.</p></div><ol className="dev-build-flow"><li><span>01</span><strong>Problema real</strong></li><li><span>02</span><strong>Elegí módulo</strong></li><li><span>03</span><strong>Sumá contexto vertical</strong></li><li><span>04</span><strong>Conectá adapter</strong></li><li><span>05</span><strong>Ajustá al cliente</strong></li><li><span>06</span><strong>Entregá</strong></li></ol></div></section>
    <section className="final-section dev-final"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>¿Qué solución querés construir?</h2><p>Contanos el problema y vemos qué combinación tiene sentido para tu próximo cliente.</p><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a></div></div></section>
  </main>;
}
function Faq() { return <section className="faq-section shell section"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Antes de empezar.</h2></div><div className="faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>; }
function App() {
  const pathname = window.location.pathname.replace(/\/+$/, "") || "/";
  const route: Route = pathname === "/ecommerce" || pathname === "/pymes" || pathname === "/devs" ? pathname : "/";
  useEffect(() => { document.title = pageMeta[route].title; const description = document.querySelector('meta[name="description"]'); if (description) description.setAttribute("content", pageMeta[route].description); }, [route]);
  const page = route === "/ecommerce" ? <CommercePage /> : route === "/pymes" ? <PymesPage /> : route === "/devs" ? <DevsPage /> : <Home />;
  return <div className={`page page-${route === "/" ? "home" : route.slice(1)}`} id="top"><a className="skip-link" href="#main-content">Saltar al contenido</a><Header />{page}{route !== "/" && <Faq />}<Footer /><a className="event-dock" href={WHATSAPP_URL}>Contanos qué querés resolver ↗</a></div>;
}
export default App;
