import { useEffect, useState, type ReactNode } from "react";
import QRCode from "qrcode";
import { adapters, commerceCases, commerceChain, commerceChecks, commerceValueBlocks, devAudiences, devModules, howSteps, questions, sellerProblems, smbAreas, smbCases, smbExcel, smbProblems, smbTools, SURVEY_URL, verticalPacks, WHATSAPP_URL } from "./data/content";

type Route = "/" | "/ecommerce" | "/pymes" | "/devs";
type Theme = "commerce" | "smb" | "devs";

const pageMeta: Record<Route, { title: string; description: string }> = {
  "/": { title: "PymIA — Operaciones conectadas", description: "PymIA conecta las herramientas que tu empresa ya usa y construye la pieza que falta." },
  "/ecommerce": { title: "E-commerce — PymIA", description: "Conectá marketplaces, sistemas y datos para vender online con menos fricción y más control." },
  "/pymes": { title: "PyMEs — PymIA", description: "Conectá administración, datos y procesos para reducir trabajo manual y ganar control." },
  "/devs": { title: "Devs — PymIA", description: "Construí soluciones empresariales con módulos, verticales y adaptadores reutilizables." },
};

function Contact({ label = "Contanos qué querés resolver" }: { label?: string }) {
  return <a className="button" href={WHATSAPP_URL}>{label} <span aria-hidden="true">↗</span></a>;
}
function Status({ children }: { children: string }) { return <span className="status-badge">{children}</span>; }

function Header() {
  return <header className="site-header shell"><a className="brand" href="/" aria-label="PymIA, volver al inicio"><img src="/logopymia2.jpg" width="56" height="56" alt="Logo de PymIA" fetchPriority="high" /><span><strong>PymIA</strong><small>Operaciones conectadas</small></span></a><nav aria-label="Navegación principal"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href="/#how">Cómo trabajamos</a><a href="/#contacto">Contacto</a><a className="nav-cta" href={SURVEY_URL}>Quiero mi VTV ↗</a></nav></header>;
}
function Footer() {
  return <footer className="shell site-footer"><span>PymIA — Buenos Aires, Argentina.</span><nav aria-label="Navegación del pie"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href={SURVEY_URL}>VTV</a><a href="/#contacto">Contacto</a></nav><a href="/#top">Volver arriba ↑</a></footer>;
}
function CommercialQr() {
  const [qr, setQr] = useState("");
  useEffect(() => { let active = true; void QRCode.toDataURL(SURVEY_URL, { width: 640, margin: 4, errorCorrectionLevel: "M", color: { dark: "#162b29", light: "#ffffff" } }).then((value) => { if (active) setQr(value); }).catch(() => { if (active) setQr(""); }); return () => { active = false; }; }, []);
  return <a className="qr-link" href={SURVEY_URL} aria-label="Abrir la VTV gratuita de PymIA">{qr && <img src={qr} width="240" height="240" alt="Código QR para abrir la VTV gratuita de PymIA" />}<span>Escaneá o tocá para completar la VTV gratuita ↗</span></a>;
}
function TrustBlock() {
  return <section className="trust-section shell section"><div><p className="eyebrow">Una forma de trabajar</p><h2>La IA ayuda a entender. PymIA controla lo que tiene que ser exacto.</h2></div><div className="trust-list"><p><strong>Evidencia.</strong> No afirmamos lo que no podemos revisar.</p><p><strong>Trazabilidad.</strong> Cada proceso deja una historia que se puede seguir.</p><p><strong>Integración.</strong> Empezamos por lo que ya existe.</p></div></section>;
}
function HowSection() {
  return <section className="how-section shell section" id="how"><div className="section-head"><div><p className="eyebrow">Cómo trabaja PymIA</p><h2>Conectar primero. Decidir mejor.</h2></div><p>Evidencia, trazabilidad y control humano: la tecnología ayuda a entender y ejecutar; la persona decide cuando corresponde.</p></div><div className="process-rail">{howSteps.map(([title, copy], index) => <article key={title}><span className="rail-dot" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>;
}
function Home() {
  return <><main id="main-content"><section className="hero shell"><div className="hero-copy"><p className="eyebrow">PymIA / operaciones conectadas</p><h1>Tu empresa ya tiene herramientas.<br /><em>PymIA hace que trabajen juntas.</em></h1><p className="hero-lede">Conectamos e-commerce, Excel, sistemas, automatizaciones e IA para reducir trabajo manual, entender lo que está pasando y construir soluciones sobre lo que ya usás.</p><div className="actions"><Contact /><a className="button button-secondary" href="#audiences">Ver soluciones ↓</a></div></div><div className="hero-aside"><div className="aside-line"><span>01</span><span>Conectar antes que reemplazar</span></div><div className="aside-line"><span>02</span><span>Reglas claras donde importan</span></div><div className="aside-line"><span>03</span><span>Personas con el control</span></div></div></section><section className="doorways shell" id="audiences"><div className="doorways-intro"><p className="eyebrow">Una marca, tres caminos</p><p>Elegí la conversación que más se parece a tu operación.</p></div><div className="doorway-grid"><a className="doorway doorway-commerce" href="/ecommerce"><span className="doorway-kicker">E-commerce</span><strong>Vendé online con menos fricción y más control.</strong><span>Marketplaces, stock, rentabilidad y datos que trabajan juntos.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar E-commerce ↗</b></a><a className="doorway doorway-smb" href="/pymes"><span className="doorway-kicker">PyMEs</span><strong>Menos trabajo manual. Más control del negocio.</strong><span>Administración, procesos y decisiones sobre información ordenada.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar soluciones para PyMEs ↗</b></a><a className="doorway doorway-devs" href="/devs"><span className="doorway-kicker">Devs</span><strong>No construyas cada solución desde cero.</strong><span>Módulos, verticales y adaptadores para implementar mejor.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar PymIA para Devs ↗</b></a></div></section><HowSection /><TrustBlock /><section className="final-section" id="contacto"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>Contanos qué querés resolver.</h2><p>Vemos qué parte de tu operación conviene conectar, ordenar o construir.</p><Contact /><p className="survey-link">También podés empezar con una revisión VTV gratuita.</p></div><CommercialQr /></div></section></main></>;
}
function ProductHero({ theme, eyebrow, title, copy, children }: { theme: Theme; eyebrow: string; title: string; copy: string; children?: ReactNode }) {
  return <section className={`product-hero section-${theme}`}><div className="shell product-hero-inner"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-lede">{copy}</p>{children}</div><div className="product-signal"><span>PYMIA</span><strong>{theme === "commerce" ? "01" : theme === "smb" ? "02" : "03"}</strong><small>línea comercial</small></div></div></section>;
}
function CommercePage() {
  return <main id="main-content">
    <ProductHero theme="commerce" eyebrow="E-commerce / sellers" title="Vendé online con más control sobre lo que realmente ganás." copy="PymIA conecta los datos de tu operación para mostrarte dónde perdés margen, tiempo o control y qué conviene corregir primero, sin obligarte a reemplazar las herramientas que ya usás.">
      <div className="actions"><a className="button button-commerce" href={SURVEY_URL}>Quiero mi VTV gratuita ↗</a><a className="button button-secondary" href="#commerce-review">Ver qué podemos revisar ↓</a></div>
    </ProductHero>
    <section className="commerce-problems shell section" id="commerce-review">
      <div className="section-head"><div><p className="eyebrow">El problema del seller</p><h2>Cuando cada dato cuenta una historia distinta.</h2></div><p>Antes de sumar otra herramienta, hacemos visible dónde se pierde plata, tiempo o control.</p></div>
      <div className="problem-list">{sellerProblems.map(([title, copy], index) => <article key={title}><span className="problem-index">0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div>
    </section>
    <section className="commerce-meli section section-commerce">
      <div className="shell section-inner"><div className="section-head"><div><p className="eyebrow">Mercado Libre</p><h2>Leemos la operación como una cadena.</h2></div><p>Una diferencia en la publicación puede terminar afectando el margen. Miramos el recorrido completo para encontrar la señal útil.</p></div>
        <ol className="operation-chain">{commerceChain.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong></li>)}</ol>
        <div className="operation-detail"><div><p className="eyebrow">Qué podemos revisar</p><p>Publicaciones, precios, órdenes, stock, Full / Flex, cargos, cobros, reclamos, devoluciones y conciliaciones.</p></div><ul className="tag-list commerce-checks">{commerceChecks.map((item) => <li key={item}>{item}</li>)}</ul><p className="commerce-note">Mercado Experience es nuestro contexto de entrada; la lectura sirve para entender tu operación completa.</p></div>
      </div>
    </section>
    <section className="vtv-feature section" id="vtv-review"><div className="shell vtv-feature-inner"><div><p className="eyebrow">La primera decisión</p><h2>Tu primera revisión: VTV PymIA.</h2><p>Contanos cómo operás, conectamos datos reales y recibís las 3 prioridades principales para saber qué corregir primero.</p><a className="button button-vtv" href={SURVEY_URL}>Hacer mi VTV ↗</a></div><div className="vtv-outcome"><div className="vtv-steps"><article><span>01</span><strong>Contanos cómo operás</strong><p>Canales, herramientas y el problema que más te preocupa.</p></article><article><span>02</span><strong>Conectamos datos reales</strong><p>Ordenamos la evidencia disponible sin pedirte cambiar todo.</p></article><article><span>03</span><strong>Recibís tus 3 prioridades</strong><p>Una lectura concreta para decidir el siguiente paso.</p></article></div><div className="vtv-deliverables"><span>Qué está sólido</span><span>Qué requiere atención</span><span>Qué no puede verificarse</span><span>Qué corregir primero</span></div></div></div></section>
    <section className="commerce-value shell section" id="commerce-value"><div className="section-head"><div><p className="eyebrow">Dónde podemos aportar claridad</p><h2>Una lectura útil antes de otra herramienta.</h2></div><p>Organizamos la conversación en cuatro frentes para que cada hallazgo tenga una decisión posible.</p></div><div className="value-list">{commerceValueBlocks.map(([title, copy], index) => <article key={title}><span className="value-index">0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="other-marketplaces section"><div className="shell other-marketplaces-inner"><div><p className="eyebrow">Más adelante</p><h2>Mercado Libre hoy. Más canales cuando tu operación lo necesite.</h2><p>Tiendanube, Shopify y otros canales pueden entrar después, cuando la base esté ordenada. No hace falta prometerlo antes.</p></div></div></section>
    <section className="commerce-cases shell section"><div className="section-head"><div><p className="eyebrow">Casos concretos</p><h2>La pregunta cambia según tu operación.</h2></div><p>El punto de partida es distinto; la prioridad tiene que ser visible.</p></div><div className="case-list">{commerceCases.map((item, index) => <article key={item}><span>0{index + 1}</span><p>{item}</p></article>)}</div></section>
    <section className="final-section commerce-final"><div className="shell final-grid"><div><p className="eyebrow">Empezá por una revisión</p><h2>Quiero mi VTV gratuita.</h2><p>Encontrá dónde conviene mirar primero, con la operación real sobre la mesa.</p><a className="button" href={SURVEY_URL}>Quiero mi VTV gratuita ↗</a></div></div></section>
  </main>;
}
function PymesPage() {
  return <main id="main-content">
    <ProductHero theme="smb" eyebrow="PyMEs / administración" title="Tu empresa no necesita otro sistema. Necesita dejar de trabajar dos veces." copy="PymIA conecta Excel, administración, cobros, ventas, stock y sistemas existentes para reducir tareas manuales, ordenar información y mostrarte dónde hay diferencias o problemas.">
      <div className="actions"><a className="button button-smb" href={WHATSAPP_URL}>Contanos qué querés resolver ↗</a><a className="button button-secondary" href="#smb-problems">Ver problemas que podemos ordenar ↓</a></div>
    </ProductHero>
    <section className="smb-problems shell section" id="smb-problems"><div className="section-head"><div><p className="eyebrow">Problemas reales</p><h2>La operación se vuelve pesada cuando cada dato vive separado.</h2></div><p>Empezamos por hacer visible el trabajo que hoy se repite y las diferencias que nadie puede explicar.</p></div><div className="smb-problem-list">{smbProblems.map(([title, copy], index) => <article key={title}><span className="smb-index">0{index + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="smb-tools section section-smb" id="smb-tools"><div className="shell section-inner"><div className="section-head"><div><p className="eyebrow">Mensaje central</p><h2>Conectamos lo que ya usás.</h2></div><p>Encontramos el hilo entre tus herramientas y el proceso real, sin obligarte a reemplazar todo tu negocio para empezar a mejorar.</p></div><div className="tool-cloud">{smbTools.map((tool) => <span key={tool}>{tool}</span>)}</div><p className="smb-tools-note">No necesitás reemplazar todo tu negocio para empezar a mejorar.</p></div></section>
    <section className="smb-areas shell section" id="smb-areas"><div className="section-head"><div><p className="eyebrow">Cuatro áreas de valor</p><h2>Del dato disperso a una decisión posible.</h2></div><p>Cada frente tiene un resultado concreto y un alcance visible.</p></div><div className="smb-area-list">{smbAreas.map(([title, headline, copy], index) => <article key={title}><span className="smb-index">0{index + 1}</span><div><p className="eyebrow">{title}</p><h3>{headline}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="excel-feature section section-smb" id="smb-excel"><div className="shell excel-feature-inner"><div><p className="eyebrow">Excel e inteligencia</p><h2>Si tu empresa vive en Excel, no significa que tengas que tirarlo.</h2><p>PymIA puede usar planillas y exportaciones como fuente de datos para analizar ventas, costos, márgenes, rentabilidad, inconsistencias y reportes.</p></div><div className="excel-panel"><Status>PILOTO</Status><ul>{smbExcel.map((item) => <li key={item}>{item}</li>)}</ul><p>El alcance se define con evidencia: algunas piezas están en piloto, en desarrollo o próximas.</p></div></div></section>
    <section className="smb-cases shell section" id="smb-cases"><div className="section-head"><div><p className="eyebrow">Casos concretos</p><h2>El problema cambia según el rubro.</h2></div><p>No prometemos soluciones completas: mostramos dónde PymIA puede ayudar a integrar y ordenar.</p></div><div className="smb-case-list">{smbCases.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="smb-flow section"><div className="shell"><div className="section-head"><div><p className="eyebrow">Cómo trabajamos</p><h2>Primero entendemos. Después automatizamos.</h2></div><p>La automatización tiene sentido cuando el proceso y sus diferencias ya son visibles.</p></div><ol className="smb-flow-list"><li><span>01</span><strong>Lo que ya usás</strong></li><li><span>02</span><strong>Conectamos</strong></li><li><span>03</span><strong>Entendemos el proceso</strong></li><li><span>04</span><strong>Detectamos diferencias</strong></li><li><span>05</span><strong>Automatizamos lo repetible</strong></li></ol><p className="smb-flow-note">Primero entendemos cómo trabaja tu empresa. Después decidimos qué vale la pena automatizar.</p></div></section>
    <section className="final-section smb-final"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>¿Dónde estás perdiendo más tiempo hoy?</h2><p>Contanos el problema y vemos qué información o proceso conviene ordenar primero.</p><a className="button" href={WHATSAPP_URL}>Contanos tu problema ↗</a></div></div></section>
  </main>;
}
function DevsPage() {
  return <main id="main-content"><ProductHero theme="devs" eyebrow="Devs / implementadores" title="Construí soluciones empresariales sin empezar cada vez desde cero." copy="Módulos empresariales, conocimiento vertical e integraciones reutilizables para construir soluciones más rápido."><div className="actions"><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a><a className="button button-secondary" href="#dev-layers">Ver las capas ↓</a></div></ProductHero><section className="shell section product-body" id="dev-layers"><div className="section-head"><div><p className="eyebrow">La composición</p><h2>Módulo + Vertical + Adapter = Solución.</h2></div><p>Una base reusable para agencias, freelancers, implementadores IA, developers y software factories pequeñas.</p></div><div className="dev-layers"><article className="layer-card"><div className="layer-heading"><span className="layer-index">01</span><div><p className="card-kicker">Capa base</p><h3>Módulos</h3></div></div><div className="pill-cloud">{devModules.map((item) => <span key={item}>{item}</span>)}</div></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">02</span><div><p className="card-kicker">Contexto de rubro</p><h3>Vertical Packs</h3></div></div><p>El módulo resuelve el proceso. El Vertical Pack aporta lenguaje, reglas, objetos y contexto del rubro.</p><div className="pill-cloud">{verticalPacks.map((item) => <span key={item}>{item}</span>)}</div></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">03</span><div><p className="card-kicker">Conexiones</p><h3>Adaptadores</h3></div></div><div className="pill-cloud">{adapters.map((item) => <span key={item}>{item}</span>)}</div></article></div><div className="solution-formula" aria-label="Módulo más vertical más adaptador igual solución"><span>Módulo</span><b>+</b><span>Vertical</span><b>+</b><span>Adapter</span><b>=</b><strong>Solución</strong><small>Presupuestos + Taller mecánico + WhatsApp</small></div><div className="dev-audience-row">{devAudiences.map((item) => <span key={item}>{item}</span>)}</div></section><section className="section-band section-devs"><div className="shell band-inner"><div><p className="eyebrow">Próximo paso</p><h2>La documentación se construye con cada implementación.</h2><p>Empezá por una pieza concreta y dejá una base que puedas volver a usar.</p></div><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a></div></section></main>;
}
function Faq() { return <section className="faq-section shell section"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Antes de empezar.</h2></div><div className="faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>; }
function App() {
  const pathname = window.location.pathname.replace(/\/+$/, "") || "/";
  const route: Route = pathname === "/ecommerce" || pathname === "/pymes" || pathname === "/devs" ? pathname : "/";
  useEffect(() => { document.title = pageMeta[route].title; const description = document.querySelector('meta[name="description"]'); if (description) description.setAttribute("content", pageMeta[route].description); }, [route]);
  const page = route === "/ecommerce" ? <CommercePage /> : route === "/pymes" ? <PymesPage /> : route === "/devs" ? <DevsPage /> : <Home />;
  return <div className={`page page-${route === "/" ? "home" : route.slice(1)}`} id="top"><a className="skip-link" href="#main-content">Saltar al contenido</a><Header />{page}{route !== "/" && <Faq />}<Footer /><a className="event-dock" href={WHATSAPP_URL}>Contanos qué querés resolver ↗</a></div>;
}
export default App;
