import { useEffect, useState, type ReactNode } from "react";
import QRCode from "qrcode";
import { adapters, commerceCards, commerceCases, devAudiences, devModules, howSteps, questions, smbCards, smbCases, SURVEY_URL, verticalPacks, WHATSAPP_URL } from "./data/content";

type Route = "/" | "/ecommerce" | "/pymes" | "/devs";
type Theme = "commerce" | "smb" | "devs";

const pageMeta: Record<Route, { title: string; description: string }> = {
  "/": { title: "PymIA — Operaciones conectadas", description: "PymIA conecta las herramientas que tu empresa ya usa y construye la pieza que falta." },
  "/ecommerce": { title: "E-commerce — PymIA", description: "Conectá marketplaces, sistemas y datos para vender online con menos fricción y más control." },
  "/pymes": { title: "PyMEs — PymIA", description: "Conectá administración, datos y procesos para reducir trabajo manual y ganar control." },
  "/devs": { title: "Devs — PymIA", description: "Construí soluciones empresariales con módulos, verticales y adaptadores reutilizables." },
};

function Contact({ label = "Contanos qué querés resolver" }: { label?: string }) {
  return <a className="button" href={WHATSAPP_URL}>{label} <span aria-hidden="true">↗</span></a>;
}
function Status({ children }: { children: string }) { return <span className="status-badge">{children}</span>; }

function Header() {
  return <header className="site-header shell"><a className="brand" href="/" aria-label="PymIA, volver al inicio"><img src="/logopymia2.jpg" width="56" height="56" alt="Logo de PymIA" fetchPriority="high" /><span><strong>PymIA</strong><small>Operaciones conectadas</small></span></a><nav aria-label="Navegación principal"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href="/#how">Cómo trabajamos</a><a href="/#contacto">Contacto</a><a className="nav-cta" href={SURVEY_URL}>Quiero mi VTV ↗</a></nav></header>;
}
function Footer() {
  return <footer className="shell site-footer"><span>PymIA — Buenos Aires, Argentina.</span><nav aria-label="Navegación del pie"><a href="/ecommerce">E-commerce</a><a href="/pymes">PyMEs</a><a href="/devs">Devs</a><a href={SURVEY_URL}>VTV</a><a href="/#contacto">Contacto</a></nav><a href="/#top">Volver arriba ↑</a></footer>;
}
function CommercialQr() {
  const [qr, setQr] = useState("");
  useEffect(() => { let active = true; void QRCode.toDataURL(SURVEY_URL, { width: 640, margin: 4, errorCorrectionLevel: "M", color: { dark: "#162b29", light: "#ffffff" } }).then((value) => { if (active) setQr(value); }).catch(() => { if (active) setQr(""); }); return () => { active = false; }; }, []);
  return <a className="qr-link" href={SURVEY_URL} aria-label="Abrir la VTV gratuita de PymIA">{qr && <img src={qr} width="240" height="240" alt="Código QR para abrir la VTV gratuita de PymIA" />}<span>Escaneá o tocá para completar la VTV gratuita ↗</span></a>;
}
function TrustBlock() {
  return <section className="trust-section shell section"><div><p className="eyebrow">Una forma de trabajar</p><h2>La IA ayuda a entender. PymIA controla lo que tiene que ser exacto.</h2></div><div className="trust-list"><p><strong>Evidencia.</strong> No afirmamos lo que no podemos revisar.</p><p><strong>Trazabilidad.</strong> Cada proceso deja una historia que se puede seguir.</p><p><strong>Integración.</strong> Empezamos por lo que ya existe.</p></div></section>;
}
function HowSection() {
  return <section className="how-section shell section" id="how"><div className="section-head"><div><p className="eyebrow">Cómo trabaja PymIA</p><h2>Conectar primero. Decidir mejor.</h2></div><p>Evidencia, trazabilidad y control humano: la tecnología ayuda a entender y ejecutar; la persona decide cuando corresponde.</p></div><div className="process-rail">{howSteps.map(([title, copy], index) => <article key={title}><span className="rail-dot" aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>;
}
function Home() {
  return <><main id="main-content"><section className="hero shell"><div className="hero-copy"><p className="eyebrow">PymIA / operaciones conectadas</p><h1>Tu empresa ya tiene herramientas.<br /><em>PymIA hace que trabajen juntas.</em></h1><p className="hero-lede">Conectamos e-commerce, Excel, sistemas, automatizaciones e IA para reducir trabajo manual, entender lo que está pasando y construir soluciones sobre lo que ya usás.</p><div className="actions"><Contact /><a className="button button-secondary" href="#audiences">Ver soluciones ↓</a></div></div><div className="hero-aside"><div className="aside-line"><span>01</span><span>Conectar antes que reemplazar</span></div><div className="aside-line"><span>02</span><span>Reglas claras donde importan</span></div><div className="aside-line"><span>03</span><span>Personas con el control</span></div></div></section><section className="doorways shell" id="audiences"><div className="doorways-intro"><p className="eyebrow">Una marca, tres caminos</p><p>Elegí la conversación que más se parece a tu operación.</p></div><div className="doorway-grid"><a className="doorway doorway-commerce" href="/ecommerce"><span className="doorway-kicker">E-commerce</span><strong>Vendé online con menos fricción y más control.</strong><span>Marketplaces, stock, rentabilidad y datos que trabajan juntos.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar E-commerce ↗</b></a><a className="doorway doorway-smb" href="/pymes"><span className="doorway-kicker">PyMEs</span><strong>Menos trabajo manual. Más control del negocio.</strong><span>Administración, procesos y decisiones sobre información ordenada.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar soluciones para PyMEs ↗</b></a><a className="doorway doorway-devs" href="/devs"><span className="doorway-kicker">Devs</span><strong>No construyas cada solución desde cero.</strong><span>Módulos, verticales y adaptadores para implementar mejor.</span><span className="doorway-arrow" aria-hidden="true">→</span><b>Explorar PymIA para Devs ↗</b></a></div></section><HowSection /><TrustBlock /><section className="final-section" id="contacto"><div className="shell final-grid"><div><p className="eyebrow">La conversación empieza acá</p><h2>Contanos qué querés resolver.</h2><p>Vemos qué parte de tu operación conviene conectar, ordenar o construir.</p><Contact /><p className="survey-link">También podés empezar con una revisión VTV gratuita.</p></div><CommercialQr /></div></section></main></>;
}
function ProductHero({ theme, eyebrow, title, copy, children }: { theme: Theme; eyebrow: string; title: string; copy: string; children?: ReactNode }) {
  return <section className={`product-hero section-${theme}`}><div className="shell product-hero-inner"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="hero-lede">{copy}</p>{children}</div><div className="product-signal"><span>PYMIA</span><strong>{theme === "commerce" ? "01" : theme === "smb" ? "02" : "03"}</strong><small>línea comercial</small></div></div></section>;
}
function CommercePage() {
  return <main id="main-content"><ProductHero theme="commerce" eyebrow="E-commerce" title="Vendé online con menos fricción y más control." copy="Conectamos tus marketplaces, sistemas y datos para ayudarte a entender rentabilidad, operación y problemas reales sin reemplazar todo lo que ya usás."><div className="actions"><a className="button button-commerce" href={SURVEY_URL}>Quiero mi VTV gratuita ↗</a><a className="button button-secondary" href="#commerce-cases">Ver casos concretos ↓</a></div></ProductHero><section className="shell section product-body" id="commerce-cases"><div className="section-head"><div><p className="eyebrow">La operación completa</p><h2>Una señal útil en cada parte.</h2></div><p>Desde publicaciones y precios hasta reclamos y conciliaciones, ordenamos la conversación alrededor de lo que necesitás decidir.</p></div><div className="product-card-grid commerce-grid">{commerceCards.map((card) => <article className="info-card" key={card.eyebrow}><div className="card-top"><span className="card-kicker">{card.eyebrow}</span><Status>{card.status}</Status></div><h3>{card.title}</h3><p>{card.copy}</p><ul className="tag-list">{card.items.map((item) => <li key={item}>{item}</li>)}</ul>{card.eyebrow === "Mercado Libre" && <a className="text-link" href={SURVEY_URL}>Quiero revisar mi operación ↗</a>}</article>)}</div><div className="case-strip"><p className="eyebrow">Casos de uso concretos</p><ul>{commerceCases.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className="section-band section-commerce"><div className="shell band-inner"><div><p className="eyebrow">Integraciones</p><h2>No necesitás empezar de cero.</h2><p>ERP, Excel, stock, facturación, CRM o sistemas propios: PymIA se integra alrededor de tu operación actual.</p></div><a className="button button-secondary" href={WHATSAPP_URL}>Quiero revisar mi operación ↗</a></div></section></main>;
}
function PymesPage() {
  return <main id="main-content"><ProductHero theme="smb" eyebrow="PyMEs" title="Tu empresa no necesita otro sistema. Necesita que los que ya usa trabajen juntos." copy="Conectamos administración, datos y procesos para reducir doble carga, ordenar información y hacer visibles los problemas que hoy quedan escondidos entre Excel, sistemas y personas."><div className="actions"><Contact label="Contanos qué proceso querés mejorar" /><a className="button button-secondary" href="#smb-cases">Ver ejemplos ↓</a></div></ProductHero><section className="shell section product-body" id="smb-cases"><div className="section-head"><div><p className="eyebrow">Procesos que se ordenan</p><h2>Más claridad para operar.</h2></div><p>No afirmamos automatizaciones completas donde todavía hay un piloto. Cada capacidad tiene un estado visible.</p></div><div className="smb-grid">{smbCards.map(([title, copy, status]) => <article className="compact-card" key={title}><div className="card-top"><span className="card-marker" aria-hidden="true">+</span><Status>{status}</Status></div><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="case-strip"><p className="eyebrow">Ejemplos por rubro</p><ul>{smbCases.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className="section-band section-smb"><div className="shell band-inner"><div><p className="eyebrow">Lo que ya existe</p><h2>Excel, ERP, WhatsApp, Mercado Pago, software propio.</h2><p>Conectamos la herramienta con el proceso, no al revés.</p></div><Contact label="Contanos qué proceso querés mejorar" /></div></section></main>;
}
function DevsPage() {
  return <main id="main-content"><ProductHero theme="devs" eyebrow="Devs / implementadores" title="Construí soluciones empresariales sin empezar cada vez desde cero." copy="Módulos empresariales, conocimiento vertical e integraciones reutilizables para construir soluciones más rápido."><div className="actions"><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a><a className="button button-secondary" href="#dev-layers">Ver las capas ↓</a></div></ProductHero><section className="shell section product-body" id="dev-layers"><div className="section-head"><div><p className="eyebrow">La composición</p><h2>Módulo + Vertical + Adapter = Solución.</h2></div><p>Una base reusable para agencias, freelancers, implementadores IA, developers y software factories pequeñas.</p></div><div className="dev-layers"><article className="layer-card"><div className="layer-heading"><span className="layer-index">01</span><div><p className="card-kicker">Capa base</p><h3>Módulos</h3></div></div><div className="pill-cloud">{devModules.map((item) => <span key={item}>{item}</span>)}</div></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">02</span><div><p className="card-kicker">Contexto de rubro</p><h3>Vertical Packs</h3></div></div><p>El módulo resuelve el proceso. El Vertical Pack aporta lenguaje, reglas, objetos y contexto del rubro.</p><div className="pill-cloud">{verticalPacks.map((item) => <span key={item}>{item}</span>)}</div></article><article className="layer-card"><div className="layer-heading"><span className="layer-index">03</span><div><p className="card-kicker">Conexiones</p><h3>Adaptadores</h3></div></div><div className="pill-cloud">{adapters.map((item) => <span key={item}>{item}</span>)}</div></article></div><div className="solution-formula" aria-label="Módulo más vertical más adaptador igual solución"><span>Módulo</span><b>+</b><span>Vertical</span><b>+</b><span>Adapter</span><b>=</b><strong>Solución</strong><small>Presupuestos + Taller mecánico + WhatsApp</small></div><div className="dev-audience-row">{devAudiences.map((item) => <span key={item}>{item}</span>)}</div></section><section className="section-band section-devs"><div className="shell band-inner"><div><p className="eyebrow">Próximo paso</p><h2>La documentación se construye con cada implementación.</h2><p>Empezá por una pieza concreta y dejá una base que puedas volver a usar.</p></div><a className="button button-dev" href={WHATSAPP_URL}>Quiero construir con PymIA ↗</a></div></section></main>;
}
function Faq() { return <section className="faq-section shell section"><div><p className="eyebrow">Preguntas frecuentes</p><h2>Antes de empezar.</h2></div><div className="faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>; }
function App() {
  const pathname = window.location.pathname.replace(/\/+$/, "") || "/";
  const route: Route = pathname === "/ecommerce" || pathname === "/pymes" || pathname === "/devs" ? pathname : "/";
  useEffect(() => { document.title = pageMeta[route].title; const description = document.querySelector('meta[name="description"]'); if (description) description.setAttribute("content", pageMeta[route].description); }, [route]);
  const page = route === "/ecommerce" ? <CommercePage /> : route === "/pymes" ? <PymesPage /> : route === "/devs" ? <DevsPage /> : <Home />;
  return <div className={`page page-${route === "/" ? "home" : route.slice(1)}`} id="top"><a className="skip-link" href="#main-content">Saltar al contenido</a><Header />{page}{route !== "/" && <Faq />}<Footer /><a className="event-dock" href={WHATSAPP_URL}>Contanos qué querés resolver ↗</a></div>;
}
export default App;
